### ISSUE TITLE
Error: Cannot return null for non-nullable field User.firstName.

### ISSUE THREAD

**Issue by YuriyGavrilov** [anssip/passlane#4]
After enter "Please enter master password:" receive an error on windows.

**Comment by anssip** [comment]
@YuriyGavrilov thanks for the bug report and sorry for the delay in response. I had email notifications turned off for this repository and I did not see this issue earlier :-(

I have a fix coming up for this tomorrow.

**Comment by anssip** [comment]
Now there is a new release 2.1.1 which should fix the problem. Please test and let me know if it works for you.
